package com.mongodb.csfle;

import static com.mongodb.client.model.Filters.eq;

import java.io.IOException;

import org.bson.Document;
import org.bson.conversions.Bson;

import com.mongodb.ConnectionString;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.model.UpdateOptions;

/*
 * Copyright 2008-present MongoDB, Inc.

 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/*
 * - Reads master key from file "master-key.txt" in root directory of project
 * - Creates a JSON schema for a specified collection to enable automatic encryption
 * - Creates an encrypted client and upserts a single document
 * - Finds the upserted document with the encrypted client using an encrypted field
 * - Attempts to find the upserted document with the normal client using an encrypted field
 * - Finds the upserted document with the normal client using a non-encrypted field
 */
public class InsertDataWithEncryptedFields {
	
	public static void main(String[] args) throws IOException {
		String connectionString = "mongodb://localhost:27017";
		String keyDb = "encryption";
		String keyColl = "__keyVault";
		String kmsProvider = "local";
		String keyVaultCollection = String.join(".", keyDb, keyColl);
		String recordsDb = "medicalRecords";
		String recordsColl = "patients";
		String keyId = "<your data encryption key>"; // paste the key generated by DataEncryptionKeyCreator here
		
		// Read the local master key from the provided file
		byte[] masterKey = CSFLEHelpers.readMasterKey("./master-key.txt");
		
		// Construct a JSON Schema
		Document schema = CSFLEHelpers.createJSONSchema(keyId);
				
		// Construct an encrypted client
		MongoClient encryptedClient = 
				CSFLEHelpers.createEncryptedClient(connectionString, kmsProvider, masterKey, keyVaultCollection, schema, recordsDb, recordsColl);

		// Insert a document into the collection
		MongoCollection<Document> collection = encryptedClient.getDatabase(recordsDb).getCollection(recordsColl);
		
		Bson ssnQuery = eq("ssn", CSFLEHelpers.SAMPLE_SSN_VALUE);
		collection.updateOne(ssnQuery, new Document("$set", CSFLEHelpers.SAMPLE_DOC), new UpdateOptions().upsert(true));
		System.out.println("Successfully upserted the sample document!");

		// Query SSN field with encrypted client
		Document result = collection.find(ssnQuery).first();
		System.out.println("Encrypted client query by the SSN (deterministically-encrypted) field:\n" + result.toJson());
		
		
		// Query SSN field with normal client without encryption
		MongoClient normalMongoClient = MongoClients.create(new ConnectionString(connectionString));
		MongoCollection<Document> normalCollection = normalMongoClient.getDatabase(recordsDb).getCollection(recordsColl);
		
		Document normalClientResult = normalCollection.find(ssnQuery).first();
		assert(normalClientResult == null) : "Check your collection documents for unencrypted SSN fields:\n" + normalClientResult;

		// Query name (non-encrypted) field with normal client without encryption
		Bson nameQuery = eq("name", CSFLEHelpers.SAMPLE_NAME_VALUE); 
		Document normalClientNameResult = normalCollection.find(nameQuery).first();
		assert(normalClientNameResult != null) : "Check your collection to ensure a document with the matching name field exists.";
		System.out.println("Query by name returned the following document:\n " + normalClientNameResult);
	}
}
